/* ==========================================================================
 *  MVB Bus Administrator configuration for MUE-API (generated by D2000)
 * --------------------------------------------------------------------------
 *  File    : mue_ba_config.c
 *  Project : MUE_API
 *  Version : d-028723
 *  Date    : 2016-09-06
 * ==========================================================================
 */


/* --------------------------------------------------------------------------
 *  Include Files
 * --------------------------------------------------------------------------
 */
#include "tcn_def.h"
#include "mue_def.h"
#include "mue_sv.h"
#include "mue_ba_config.h"


/* --------------------------------------------------------------------------
 *  Periodic_List (i.e. Cyclic Process Data
 *  Remark: Use for procedure "mue_sv_put_ba_config()"
 * --------------------------------------------------------------------------
 */
#define MUE_BA_CFG_PL_CNT 130
TCN_DECL_LOCAL TCN_DECL_CONST
WORD16
mue_ba_cfg_pl[] = \
{                 \
    /* slot    1 */ 0x4200, 0x4300, 0xA001, \
    /* slot    2 */ 0xA002, \
    /* slot    3 */ 0xA003, \
    /* slot    4 */ 0xA004, \
    /* slot    5 */ 0xA005, \
    /* slot    6 */ 0xA006, \
    /* slot    7 */ 0xA007, \
    /* slot    8 */ 0xA008, \
    /* slot    9 */ 0xA009, \
    /* slot   10 */ 0xA00A, \
    /* slot   11 */ 0xA00B, \
    /* slot   12 */ 0xA00C, \
    /* slot   13 */ 0xA00D, \
    /* slot   14 */ 0xA00E, \
    /* slot   15 */ 0xA00F, \
    /* slot   16 */ 0xA010, \
    /* slot   17 */ 0xA011, \
    /* slot   18 */ 0xA012, \
    /* slot   19 */ 0xA013, \
    /* slot   20 */ 0xA014, \
    /* slot   21 */ 0xA015, \
    /* slot   22 */ 0xA016, \
    /* slot   23 */ 0xA017, \
    /* slot   24 */ 0xA018, \
    /* slot   25 */ 0xA019, \
    /* slot   26 */ 0xA01A, \
    /* slot   27 */ 0xA01B, \
    /* slot   28 */ 0xA01C, \
    /* slot   29 */ 0xA01D, \
    /* slot   30 */ 0xA01E, \
    /* slot   31 */ 0xA01F, \
    /* slot   32 */ 0xA020, \
    /* slot   33 */ 0xA021, \
    /* slot   34 */ 0xA022, \
    /* slot   35 */ 0xA023, \
    /* slot   36 */ 0xA024, \
    /* slot   37 */ 0xA025, \
    /* slot   38 */ 0xA026, \
    /* slot   39 */ 0xA027, \
    /* slot   40 */ 0xA028, \
    /* slot   41 */ 0xA029, \
    /* slot   42 */ 0xA02A, \
    /* slot   43 */ 0xA02B, \
    /* slot   44 */ 0xA02C, \
    /* slot   45 */ 0xA02D, \
    /* slot   46 */ 0xA02E, \
    /* slot   47 */ 0xA02F, \
    /* slot   48 */ 0xA030, \
    /* slot   49 */ 0xA031, \
    /* slot   50 */ 0xA032, \
    /* slot   51 */ 0xA033, \
    /* slot   52 */ 0xA034, \
    /* slot   53 */ 0xA035, \
    /* slot   54 */ 0xA036, \
    /* slot   55 */ 0xA037, \
    /* slot   56 */ 0xA038, \
    /* slot   57 */ 0xA039, \
    /* slot   58 */ 0xA03A, \
    /* slot   59 */ 0xA03B, \
    /* slot   60 */ 0xA03C, \
    /* slot   61 */ 0xA03D, \
    /* slot   62 */ 0xA03E, \
    /* slot   63 */ 0xA03F, \
    /* slot   64 */ 0xA040, \
    /* slot   65 */ 0xA041, \
    /* slot   66 */ 0xA042, \
    /* slot   67 */ 0xA043, \
    /* slot   68 */ 0xA044, \
    /* slot   69 */ 0xA045, \
    /* slot   70 */ 0xA046, \
    /* slot   71 */ 0xA047, \
    /* slot   72 */ 0xA048, \
    /* slot   73 */ 0xA049, \
    /* slot   74 */ 0xA04A, \
    /* slot   75 */ 0xA04B, \
    /* slot   76 */ 0xA04C, \
    /* slot   77 */ 0xA04D, \
    /* slot   78 */ 0xA04E, \
    /* slot   79 */ 0xA04F, \
    /* slot   80 */ 0xA050, \
    /* slot   81 */ 0xA051, \
    /* slot   82 */ 0xA052, \
    /* slot   83 */ 0xA053, \
    /* slot   84 */ 0xA054, \
    /* slot   85 */ 0xA055, \
    /* slot   86 */ 0xA056, \
    /* slot   87 */ 0xA057, \
    /* slot   88 */ 0xA058, \
    /* slot   89 */ 0xA059, \
    /* slot   90 */ 0xA05A, \
    /* slot   91 */ 0xA05B, \
    /* slot   92 */ 0xA05C, \
    /* slot   93 */ 0xA05D, \
    /* slot   94 */ 0xA05E, \
    /* slot   95 */ 0xA05F, \
    /* slot   96 */ 0xA060, \
    /* slot   97 */ 0xA061, \
    /* slot   98 */ 0xA062, \
    /* slot   99 */ 0xA063, \
    /* slot  100 */ 0xA064, \
    /* slot  101 */ 0xA065, \
    /* slot  102 */ 0xA066, \
    /* slot  103 */ 0xA067, \
    /* slot  104 */ 0xA068, \
    /* slot  105 */ 0xA069, \
    /* slot  106 */ 0xA06A, \
    /* slot  107 */ 0xA06B, \
    /* slot  108 */ 0xA06C, \
    /* slot  109 */ 0xA06D, \
    /* slot  110 */ 0xA06E, \
    /* slot  111 */ 0xA06F, \
    /* slot  112 */ 0xA070, \
    /* slot  113 */ 0xA071, \
    /* slot  114 */ 0xA072, \
    /* slot  115 */ 0xA073, \
    /* slot  116 */ 0xA074, \
    /* slot  117 */ 0xA075, \
    /* slot  118 */ 0xA076, \
    /* slot  119 */ 0xA077, \
    /* slot  120 */ 0xA078, \
    /* slot  121 */ 0xA079, \
    /* slot  122 */ 0xA07A, \
    /* slot  123 */ 0xA07B, \
    /* slot  124 */ 0xA07C, \
    /* slot  125 */ 0xA07D, \
    /* slot  126 */ 0xA07E, \
    /* slot  127 */ 0xA07F, \
    /* slot  128 */ 0xAFFF \
}; /* mue_ba_cfg_pl[] */


#ifdef MUE_BA_CONFIG_PROCEDURE

/* --------------------------------------------------------------------------
 *  Procedure "mue_ba_config()"
 * --------------------------------------------------------------------------
 */
TCN_DECL_PUBLIC
MUE_RESULT
mue_ba_config
(
    void        *p_bus_ctrl
)
{
    MUE_RESULT              mue_result;
    TCN_DECL_CONST WORD16   *p_ba_cfg_pl;
    UNSIGNED16              ba_pl_cfg_cnt;
    TCN_DECL_CONST WORD16   *p_ba_cfg_kdl;
    UNSIGNED16              ba_kdl_cfg_cnt;

    p_ba_cfg_pl    = mue_ba_cfg_pl;
    ba_pl_cfg_cnt  = (UNSIGNED16)MUE_BA_CFG_PL_CNT;
    p_ba_cfg_kdl   = NULL;
    ba_kdl_cfg_cnt = (UNSIGNED16)0;
    mue_result =            \
        mue_sv_ba_config    \
        (                   \
            p_bus_ctrl,     \
            p_ba_cfg_pl,    \
            ba_pl_cfg_cnt,  \
            p_ba_cfg_kdl,   \
            ba_kdl_cfg_cnt  \
        );

    return(mue_result);

} /* mue_ba_config */

#endif /* #ifdef MUE_BA_CONFIG_PROCEDURE */
