#ifndef MUE_BA_CONFIG_H
#define MUE_BA_CONFIG_H

/* ==========================================================================
 *  MVB Bus Administrator configuration for MUE-API (generated by D2000)
 * --------------------------------------------------------------------------
 *  File    : mue_ba_config.h
 *  Project : MUE_API
 *  Version : d-028723
 *  Date    : 2016-09-06
 * ==========================================================================
 */


/* --------------------------------------------------------------------------
 *  Include Files
 * --------------------------------------------------------------------------
 */
#include "tcn_def.h"
#include "mue_def.h"
#define MUE_BA_CONFIG_PROCEDURE

#ifdef MUE_BA_CONFIG_PROCEDURE

/* --------------------------------------------------------------------------
 *  Procedure "mue_ba_config()"
 * --------------------------------------------------------------------------
 */
TCN_DECL_PUBLIC
MUE_RESULT
mue_ba_config
(
    void        *p_bus_ctrl
);

#endif /* #ifdef MUE_BA_CONFIG_PROCEDURE */


#endif /* #ifndef MUE_BA_CONFIG_H */
